# -*- coding: utf-8 -*-
"""código do tcc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnSE6XCOIHYwKloNo0LSjnFdWXLAqOYB
"""

# Célula Colab: Buscar PubMed (últimos 10 anos) e salvar CSV + RIS
!pip install --quiet biopython pandas tqdm

from Bio import Entrez, Medline
import pandas as pd
from tqdm import tqdm
import time

# --- CONFIGURAÇÃO (edite seu e-mail) ---
Entrez.email = "wesleyfeliipe.fc@gmail.com"   # <--- substitua pelo seu e-mail
# Entrez.api_key = "YOUR_NCBI_API_KEY"   # opcional para aumentar limite de taxa

# --- PARÂMETROS DA BUSCA ---
query_core = ('(microRNA[Title/Abstract] OR miRNA[Title/Abstract] OR "micro-RNA"[Title/Abstract]) '
              'AND (Alzheimer[Title/Abstract] OR Parkinson[Title/Abstract] OR neurodegenerat*[Title/Abstract]) '
              'AND (expression[Title/Abstract] OR biomarker[Title/Abstract] OR epigenetic[Title/Abstract] '
              'OR methylation[Title/Abstract] OR "expression profiling"[Title/Abstract] OR "RNA-seq"[Title/Abstract] '
              'OR microarray[Title/Abstract])')

# filtro de data (últimos 10 anos: 2015-01-01 até 2025-10-21)
date_from = "2015/01/01"
date_to = "2025/10/21"   # data de corte conforme seu fuso/escopo
date_filter = f' AND ("{date_from}"[PDAT] : "{date_to}"[PDAT])'

query = query_core + date_filter
print("Query usada:\n", query)

# quantidade máxima a recuperar nesta execução (ajuste conforme necessidade)
MAX_RESULTS = 1000

# --- 1) Buscar PMIDs (esearch) ---
search_handle = Entrez.esearch(db="pubmed", term=query, retmax=MAX_RESULTS, usehistory="y")
search_results = Entrez.read(search_handle)
search_handle.close()

total_found = int(search_results["Count"])
pmids = search_results["IdList"]
print(f"Total de registros no PubMed (query + período): {total_found}")
print(f"Baixando os primeiros {len(pmids)} PMIDs (retmax={MAX_RESULTS})")

# --- 2) Recuperar detalhes (efetch Medline) em lotes ---
records = []
BATCH = 200
for i in tqdm(range(0, len(pmids), BATCH)):
    batch = pmids[i:i+BATCH]
    handle = Entrez.efetch(db="pubmed", id=",".join(batch), rettype="medline", retmode="text")
    parsed = Medline.parse(handle)
    for rec in parsed:
        pmid = rec.get("PMID","")
        title = rec.get("TI","")
        abstract = rec.get("AB","")
        journal = rec.get("JT","")
        year = rec.get("DP","").split()[0] if rec.get("DP") else ""
        authors = "; ".join(rec.get("AU", []))
        mesh = "; ".join(rec.get("MH", []))
        records.append({
            "PMID": pmid,
            "Title": title,
            "Abstract": abstract,
            "Journal": journal,
            "Year": year,
            "Authors": authors,
            "MeSH": mesh
        })
    handle.close()
    time.sleep(0.4)  # cortesia ao NCBI

# --- 3) Salvar CSV e RIS (pronto para Rayyan/Zotero) ---
df = pd.DataFrame(records)
CSV_OUT = "pubmed_results_2015_2025.csv"
RIS_OUT = "pubmed_results_2015_2025.ris"
df.to_csv(CSV_OUT, index=False, encoding="utf-8")
print(f"CSV salvo: {CSV_OUT}")

def to_ris(rec):
    ris = ["TY  - JOUR"]
    if rec.get("Authors"):
        for au in rec["Authors"].split("; "):
            ris.append(f"AU  - {au}")
    ris.append(f"TI  - {rec.get('Title','')}")
    if rec.get("Journal"):
        ris.append(f"JO  - {rec.get('Journal')}")
    if rec.get("Year"):
        ris.append(f"PY  - {rec.get('Year')}")
    if rec.get("Abstract"):
        ris.append(f"AB  - {rec.get('Abstract')}")
    ris.append(f"ID  - {rec.get('PMID')}")
    ris.append("ER  - ")
    return "\n".join(ris)

with open(RIS_OUT, "w", encoding="utf-8") as fh:
    for _, r in df.iterrows():
        fh.write(to_ris(r) + "\n")

print(f"RIS salvo: {RIS_OUT}")

# --- 4) Mostrar preview (primeiros 30 registros) ---
from IPython.display import display
display(df.head(30))



# ============================================
# 0) Setup (executar no Google Colab)
# ============================================
# Se necessário, monte o Drive:
# from google.colab import drive
# drive.mount('/content/drive')

import re
import math
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

plt.rcParams.update({"figure.dpi": 150})
# (Não definir cores/estilos explicitamente para cumprir exigências.)

# Caminho do CSV (ajuste conforme o seu ambiente)
CSV_PATH = "/content/pubmed_results_2015_2025.csv"

# ============================================
# 1) Carregar & normalizar
# ============================================
df = pd.read_csv(CSV_PATH)
for col in ["Title", "Abstract", "Keywords", "Authors", "Journal"]:
    if col not in df.columns:
        df[col] = ""
df["Year"] = pd.to_numeric(df.get("Year", np.nan), errors="coerce")

df["Title_lower"] = df["Title"].astype(str).str.lower()
df["Abstract_lower"] = df["Abstract"].astype(str).str.lower()
df["Keywords_lower"] = df["Keywords"].astype(str).str.lower()

# ============================================
# 2) Scoring de relevância (ranqueamento)
#    - Pesos maiores no Título, médios em Abstract e pequenos em Keywords
# ============================================
keywords = [
    "mirna", "microrna", "micro-rna",
    "epigenet", "methylation", "histone",
    "alzheimer", "parkinson",
    "biomarker", "expression", "profiling",
    "exosome", "extracellular vesicle", "csf", "plasma", "serum",
    "brain", "cortex", "hippocampus", "substantia nigra", "striatum"
]
def score_row(row):
    t = row["Title_lower"]
    a = row["Abstract_lower"]
    k = row["Keywords_lower"]
    s = 0
    for kw in keywords:
        if kw in t: s += 3
        if kw in a: s += 2
        if kw in k: s += 1
    return s

df["relevance_score"] = df.apply(score_row, axis=1)
df_scored = df[df["relevance_score"] > 0].copy()
df_scored = df_scored.sort_values(["relevance_score","Year"], ascending=[False, False])

# ============================================
# 3) Seleção Top 100 + anotações automáticas
# ============================================
topN = 100
top_df = df_scored.head(topN).copy().reset_index(drop=True)

def detect_disease(text):
    t = str(text).lower()
    has_ad = any(x in t for x in ["alzheimer", "alzheimer’s", "alzheimer's"])
    has_pd = any(x in t for x in ["parkinson", "parkinson’s", "parkinson's"])
    if has_ad and has_pd: return "AD+PD"
    if has_ad: return "AD"
    if has_pd: return "PD"
    return "Indefinido"

def detect_study_type(text):
    t = str(text).lower()
    if "systematic review" in t or "meta-analysis" in t or "meta analysis" in t:
        return "Revisão/Meta-análise"
    if "review" in t:
        return "Revisão"
    clinical = ["case-control","cohort","cross-sectional","clinical","trial","patients","controls"]
    if any(x in t for x in clinical): return "Primário (clínico)"
    preclin = ["in vitro","cell","cells","neuron","neuronal","mouse","mice","rat","animal","drosophila","zebrafish"]
    if any(x in t for x in preclin): return "Primário (pré-clínico)"
    return "Indefinido"

def detect_method(text):
    t = str(text).lower()
    if "rna-seq" in t or "rna seq" in t or "small rna" in t or "next-generation sequencing" in t:
        return "RNA-seq/smallRNA-seq"
    if "qpcr" in t or "rt-qpcr" in t or "real-time pcr" in t or "rt-pcr" in t or "pcr" in t:
        return "qPCR/RT-qPCR"
    if "microarray" in t: return "Microarray"
    if "nanostring" in t: return "NanoString"
    if "bioinformatic" in t or "in silico" in t or "computational" in t:
        return "Bioinformática"
    return "Indefinido"

def detect_sample(text):
    t = str(text).lower()
    sample_map = [
        ("CSF", ["csf","cerebrospinal fluid"]),
        ("Plasma", ["plasma"]),
        ("Soro", ["serum"]),
        ("Sangue total", ["whole blood","peripheral blood","blood sample","blood plasma","blood serum"]),
        ("Cérebro/tecido", ["brain","hippocampus","cortex","prefrontal","substantia nigra","striatum","temporal","frontal"]),
        ("Exossomos/EVs", ["exosome","exosomes","extracellular vesicle","extracellular vesicles","evs"]),
    ]
    found = []
    for label, keys in sample_map:
        if any(k in t for k in keys):
            found.append(label)
    return "; ".join(sorted(set(found))) if found else "Indefinido"

mirna_pattern = re.compile(r'\bmiR[- ]?\d+[a-z]?(?:-\d+)?[a-z]?(?:-\d+)?\b', re.IGNORECASE)
def extract_mirnas(text):
    s = str(text)
    hits = mirna_pattern.findall(s)
    norm = []
    for m in hits:
        m = m.replace(" ", "-")
        m = "miR-" + m.split("miR-")[-1]
        norm.append(m)
    # únicos preservando ordem
    seen, uniq = set(), []
    for x in norm:
        if x not in seen:
            seen.add(x)
            uniq.append(x)
    return ", ".join(uniq[:12])

combo = (top_df["Title"].fillna("") + " " + top_df["Abstract"].fillna("")).astype(str)
top_df["Doença (auto)"] = combo.apply(detect_disease)
top_df["Tipo de Estudo (auto)"] = combo.apply(detect_study_type)
top_df["Método (auto)"] = combo.apply(detect_method)
top_df["Amostra (auto)"] = combo.apply(detect_sample)
top_df["miRNAs citados (auto)"] = combo.apply(extract_mirnas)

# Salvar planilha anotada
cols_out = ["PMID","Title","Authors","Year","Journal",
            "Doença (auto)","Tipo de Estudo (auto)","Método (auto)",
            "Amostra (auto)","miRNAs citados (auto)","Abstract","Keywords"]
top_df[cols_out].to_csv("/content/top100_miRNA_AD_PD_annotated.csv", index=False)

# ============================================
# 4) Estatísticas & gráficos (matplotlib puro)
# ============================================
pubs_by_year = top_df["Year"].value_counts().sort_index()
by_disease = top_df["Doença (auto)"].value_counts()
by_type = top_df["Tipo de Estudo (auto)"].value_counts()
by_sample = top_df["Amostra (auto)"].value_counts()

# 4.1 Publicações por ano
plt.figure(figsize=(7,4))
pubs_by_year.plot(kind="bar")
plt.title("Publicações por ano (Top 100)")
plt.xlabel("Ano")
plt.ylabel("Número de publicações")
plt.tight_layout()
plt.savefig("/content/graf_publicacoes_por_ano.png")
plt.close()

# 4.2 Distribuição por doença
plt.figure(figsize=(6,4))
by_disease.plot(kind="bar")
plt.title("Distribuição por doença (Top 100)")
plt.xlabel("Categoria")
plt.ylabel("Número de publicações")
plt.tight_layout()
plt.savefig("/content/graf_por_doenca.png")
plt.close()

# 4.3 Distribuição por tipo de estudo
plt.figure(figsize=(6,4))
by_type.plot(kind="bar")
plt.title("Distribuição por tipo de estudo (Top 100)")
plt.xlabel("Tipo de estudo")
plt.ylabel("Número de publicações")
plt.tight_layout()
plt.savefig("/content/graf_por_tipo_estudo.png")
plt.close()

# 4.4 Distribuição por amostra
plt.figure(figsize=(7,4))
by_sample.plot(kind="bar")
plt.title("Distribuição por tipo de amostra (Top 100)")
plt.xlabel("Amostra")
plt.ylabel("Número de publicações")
plt.tight_layout()
plt.savefig("/content/graf_por_amostra.png")
plt.close()

# 4.5 Top miRNAs (na Title/Abstract)
all_mirnas = []
for s in top_df["miRNAs citados (auto)"]:
    if isinstance(s, str) and s.strip():
        all_mirnas.extend([x.strip() for x in s.split(",") if x.strip()])
miRNA_counts = pd.Series(Counter(all_mirnas)).sort_values(ascending=False).head(30)

plt.figure(figsize=(7,7))
miRNA_counts.sort_values(ascending=True).plot(kind="barh")
plt.title("Top miRNAs citados (Título/Abstract) – Top 100")
plt.xlabel("Frequência")
plt.ylabel("miRNA")
plt.tight_layout()
plt.savefig("/content/graf_top_miRNAs.png")
plt.close()

# ============================================
# 5) PCA opcional (texto -> vetores TF-IDF pode ser pesado; aqui PCA em features simples)
# ============================================
# Exemplo simples: matriz binária de presença de categorias
feats = pd.get_dummies(top_df[["Doença (auto)","Tipo de Estudo (auto)","Método (auto)","Amostra (auto)"]])
X = feats.values
if X.shape[0] > 2 and X.shape[1] > 2:
    scaler = StandardScaler(with_mean=True, with_std=True)
    Xz = scaler.fit_transform(X)
    pca = PCA(n_components=2, random_state=42)
    Z = pca.fit_transform(Xz)
    plt.figure(figsize=(6,5))
    plt.scatter(Z[:,0], Z[:,1])
    plt.title("PCA (metadados categóricos) – Top 100")
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.tight_layout()
    plt.savefig("/content/graf_pca.png")
    plt.close()

# ============================================
# 6) Arquivos de saída principais
# ============================================
top_df[cols_out].to_excel("/content/Tabela_Mestra_Top100.xlsx", index=False)

# Resumos CSV para gráficos (úteis no TCC)
pubs_by_year.to_csv("/content/summary_publicacoes_por_ano.csv", header=["Publicações"])
by_disease.to_csv("/content/summary_por_doenca.csv", header=["Publicações"])
by_type.to_csv("/content/summary_por_tipo_estudo.csv", header=["Publicações"])
by_sample.to_csv("/content/summary_por_amostra.csv", header=["Publicações"])
miRNA_counts.to_csv("/content/summary_top_miRNAs.csv", header=["Frequência"])

print("Pronto! Gerados: Tabela_Mestra_Top100.xlsx + PNGs + summaries CSV.")