# -*- coding: utf-8 -*-
"""TCC_epigenética-continuação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLPT65PaZXr7H7A0RvnKPQnyy4hleZdq

# ETAPA 1 — AUDITORIA E ESTATÍSTICA DESCRITIVA
"""

import pandas as pd
import numpy as np
import re
from collections import Counter
from scipy.stats import chi2_contingency

top100 = pd.read_csv("top100_miRNA_AD_PD_annotated.csv")
pubmed = pd.read_csv("pubmed_results_2015_2025.csv")

print("Base PubMed:", pubmed.shape)
print("Top 100:", top100.shape)

print("\nDistribuição por doença:")
print(top100["Doença (auto)"].value_counts())

print("\nDistribuição por tipo de estudo:")
print(top100["Tipo de Estudo (auto)"].value_counts())

print("\nDistribuição por método:")
print(top100["Método (auto)"].value_counts())

print("\nDistribuição por amostra:")
print(top100["Amostra (auto)"].value_counts().head(15))

# Teste qui-quadrado: doença x método
tabela = pd.crosstab(
    top100["Doença (auto)"],
    top100["Método (auto)"]
)

chi2, p, dof, expected = chi2_contingency(tabela)

print("Tabela doença x método:")
print(tabela)

print("\nQui-quadrado:", chi2)
print("p-valor:", p)
print("Graus de liberdade:", dof)

"""EXTRAÇÃO E RANKING DE miRNAs"""

# corrigir extração + limpeza

import re

def extract_and_clean(text):
    if pd.isna(text):
        return []

    # extrai miRNAs
    mirs = re.findall(r'miR-\d+[a-zA-Z0-9\-]*', str(text))

    # limpa hífen final e padroniza
    mirs = [m.rstrip('-').lower() for m in mirs]

    return mirs

top100["miRNAs_list"] = top100[col_mirna].apply(extract_and_clean)

from collections import Counter

ad = top100[top100["Doença (auto)"] == "AD"]
pd_df = top100[top100["Doença (auto)"] == "PD"]

ad_mirnas = Counter([mir for sublist in ad["miRNAs_list"] for mir in sublist])
pd_mirnas = Counter([mir for sublist in pd_df["miRNAs_list"] for mir in sublist])

print("Top miRNAs em Alzheimer:")
print(ad_mirnas.most_common(15))

print("\nTop miRNAs em Parkinson:")
print(pd_mirnas.most_common(15))

"""ETAPA 3 (estrutura matemática)"""

# ETAPA 3 — MATRIZ miRNA x DOENÇA

import pandas as pd

# top 15 de cada
top_ad = dict(ad_mirnas.most_common(15))
top_pd = dict(pd_mirnas.most_common(15))

# união
all_mirnas = list(set(list(top_ad.keys()) + list(top_pd.keys())))

# criar matriz
data = []

for mir in all_mirnas:
    data.append([
        mir,
        top_ad.get(mir, 0),
        top_pd.get(mir, 0)
    ])

df_matrix = pd.DataFrame(data, columns=["miRNA", "AD", "PD"])

print(df_matrix)

"""ETAPA 4 — PCA (Machine Learning)"""

# ETAPA 4 — PCA

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# preparar dados
X = df_matrix[["AD", "PD"]]

# PCA
pca = PCA(n_components=2)
components = pca.fit_transform(X)

df_matrix["PC1"] = components[:, 0]
df_matrix["PC2"] = components[:, 1]

# plot
plt.figure()
plt.scatter(df_matrix["PC1"], df_matrix["PC2"])

for i, txt in enumerate(df_matrix["miRNA"]):
    plt.text(df_matrix["PC1"][i], df_matrix["PC2"][i], txt, fontsize=8)

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA dos miRNAs (AD vs PD)")
plt.show()

"""ARTIGOS → miRNAs (presença/ausência)"""

# ETAPA 5 — MATRIZ BINÁRIA (ARTIGO x miRNA)

from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

# transformar lista de miRNAs em matriz binária
X = mlb.fit_transform(top100["miRNAs_list"])

df_binary = pd.DataFrame(X, columns=mlb.classes_)

print(df_binary.shape)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
components = pca.fit_transform(df_binary)

top100["PC1"] = components[:, 0]
top100["PC2"] = components[:, 1]

plt.figure()
plt.scatter(top100["PC1"], top100["PC2"])

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA baseado em artigos (miRNA profile)")
plt.show()

import matplotlib.pyplot as plt

colors = {
    "AD": 0,
    "PD": 1,
    "AD+PD": 2,
    "Indefinido": 3
}

plt.figure()

for d in top100["Doença (auto)"].unique():
    subset = top100[top100["Doença (auto)"] == d]
    plt.scatter(subset["PC1"], subset["PC2"], label=d)

plt.legend()
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA por doença")
plt.show()

# identificar outliers

top100_sorted = top100.sort_values(by="PC1", ascending=False)
print(top100_sorted[["Title", "Doença (auto)", "PC1", "PC2"]].head(5))

"""ETAPA 6 — CLUSTERING (ESSENCIAL)"""

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
top100["Cluster"] = kmeans.fit_predict(df_binary)

import matplotlib.pyplot as plt

plt.figure()

for c in top100["Cluster"].unique():
    subset = top100[top100["Cluster"] == c]
    plt.scatter(subset["PC1"], subset["PC2"], label=f"Cluster {c}")

plt.legend()
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Clusters de miRNAs em estudos neurodegenerativos")
plt.show()

"""ETAPA 6.1 — entender biologicamente cada cluster"""

# ver distribuição por cluster

for c in sorted(top100["Cluster"].unique()):
    print(f"\n=== CLUSTER {c} ===")

    subset = top100[top100["Cluster"] == c]

    print("Doenças:")
    print(subset["Doença (auto)"].value_counts())

    print("\nTop miRNAs:")
    mirnas = [mir for sublist in subset["miRNAs_list"] for mir in sublist]
    from collections import Counter
    print(Counter(mirnas).most_common(10))

"""ETAPA FINAL — REDE miRNA–DOENÇA"""

# ETAPA FINAL — REDE miRNA-DOENÇA

import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

# adicionar nós de doenças
diseases = ["AD", "PD"]
G.add_nodes_from(diseases, type="disease")

# adicionar miRNAs (top 10 de cada)
for mir, count in ad_mirnas.most_common(10):
    G.add_node(mir, type="mirna")
    G.add_edge("AD", mir, weight=count)

for mir, count in pd_mirnas.most_common(10):
    G.add_node(mir, type="mirna")
    G.add_edge("PD", mir, weight=count)

# plot
plt.figure()
pos = nx.spring_layout(G)

nx.draw(G, pos, with_labels=True)
plt.title("Rede miRNA–Doença")
plt.show()

"""simulações"""

import numpy as np
import plotly.graph_objects as go

mirna = np.linspace(0, 2, 60)
tempo = np.linspace(0, 100, 60)

MIRNA, TEMPO = np.meshgrid(mirna, tempo)

alpha = 1.0
beta = 0.8
delta = 0.1

MRNA = alpha / (beta * MIRNA + delta + 1e-6)

fig = go.Figure(data=[
    go.Surface(
        x=MIRNA,
        y=TEMPO,
        z=MRNA
    )
])

fig.update_layout(
    title="Superfície 3D da repressão de mRNA por miRNA",
    scene=dict(
        xaxis_title="Nível de miRNA",
        yaxis_title="Tempo",
        zaxis_title="Expressão relativa de mRNA"
    )
)

fig.show()

"""Simulação dinâmica miRNA–mRNA"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

def model(t, y, alpha, beta, delta, mirna):
    mrna = y[0]
    dmrna_dt = alpha - beta * mirna * mrna - delta * mrna
    return [dmrna_dt]

t_span = (0, 100)
t_eval = np.linspace(0, 100, 500)

params = {
    "Baixo miRNA": 0.2,
    "Moderado miRNA": 0.8,
    "Alto miRNA": 1.5
}

plt.figure(figsize=(9, 5))

for label, mirna_level in params.items():
    sol = solve_ivp(
        model,
        t_span,
        y0=[1.0],
        t_eval=t_eval,
        args=(1.0, 0.8, 0.1, mirna_level)
    )
    plt.plot(sol.t, sol.y[0], label=label)

plt.xlabel("Tempo")
plt.ylabel("Expressão relativa de mRNA")
plt.title("Simulação dinâmica da repressão de mRNA por miRNA")
plt.legend()
plt.tight_layout()
plt.show()

import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

for disease in ["AD", "PD"]:
    subset = top100[top100["Doença (auto)"] == disease]
    mirnas = [m for sublist in subset["miRNAs_list"] for m in sublist]
    counts = Counter(mirnas)

    G.add_node(disease, node_type="disease")

    for mir, count in counts.most_common(12):
        G.add_node(mir, node_type="mirna")
        G.add_edge(disease, mir, weight=count)

pos = nx.spring_layout(G, seed=42, k=0.7)

plt.figure(figsize=(12, 9))
weights = [G[u][v]["weight"] for u, v in G.edges()]

nx.draw_networkx_nodes(G, pos, node_size=900)
nx.draw_networkx_edges(G, pos, width=weights)
nx.draw_networkx_labels(G, pos, font_size=9)

plt.title("Rede miRNA–doença baseada em frequência bibliométrica")
plt.axis("off")
plt.show()

"""**modelo AD: miR-29c/miR-107 → BACE1 → Aβ → neuroinflamação → morte neuronal.**"""

# ======================================================
# SIMULAÇÃO 1 — VIA AD: miR-29c / miR-107 → BACE1 → Aβ
# ======================================================

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# Variáveis:
# y[0] = BACE1
# y[1] = Aβ
# y[2] = Neuroinflamação
# y[3] = Sobrevivência neuronal

def modelo_AD(t, y, mirna, params):
    BACE1, Abeta, inflam, neuron = y

    alpha_bace1 = params["alpha_bace1"]
    beta_mirna = params["beta_mirna"]
    delta_bace1 = params["delta_bace1"]

    alpha_abeta = params["alpha_abeta"]
    delta_abeta = params["delta_abeta"]

    alpha_inflam = params["alpha_inflam"]
    delta_inflam = params["delta_inflam"]

    beta_neuron = params["beta_neuron"]

    dBACE1_dt = alpha_bace1 - beta_mirna * mirna * BACE1 - delta_bace1 * BACE1
    dAbeta_dt = alpha_abeta * BACE1 - delta_abeta * Abeta
    dInflam_dt = alpha_inflam * Abeta - delta_inflam * inflam
    dNeuron_dt = - beta_neuron * inflam * neuron

    return [dBACE1_dt, dAbeta_dt, dInflam_dt, dNeuron_dt]


params_AD = {
    "alpha_bace1": 1.0,
    "beta_mirna": 0.8,
    "delta_bace1": 0.15,
    "alpha_abeta": 0.7,
    "delta_abeta": 0.12,
    "alpha_inflam": 0.5,
    "delta_inflam": 0.1,
    "beta_neuron": 0.015
}

tempo = (0, 100)
t_eval = np.linspace(0, 100, 500)

condicoes = {
    "Controle": 1.0,
    "Doença AD - baixo miRNA": 0.25,
    "Terapia mimic miR-29c/miR-107": 1.8
}

resultados_AD = {}

for nome, mirna in condicoes.items():
    sol = solve_ivp(
        modelo_AD,
        tempo,
        y0=[1.0, 0.5, 0.3, 1.0],
        t_eval=t_eval,
        args=(mirna, params_AD)
    )
    resultados_AD[nome] = sol

variaveis = ["BACE1", "β-amiloide (Aβ)", "Neuroinflamação", "Sobrevivência neuronal"]

for i, var in enumerate(variaveis):
    plt.figure(figsize=(8, 5))

    for nome, sol in resultados_AD.items():
        plt.plot(sol.t, sol.y[i], label=nome)

    plt.xlabel("Tempo simulado")
    plt.ylabel("Nível relativo")
    plt.title(f"Simulação AD — {var}")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""**Impacto sistêmico completo **"""

# visualizar todas as variáveis

variaveis = ["BACE1", "β-amiloide", "Neuroinflamação", "Sobrevivência neuronal"]

for i, var in enumerate(variaveis):
    plt.figure()

    for nome, sol in resultados_AD.items():
        plt.plot(sol.t, sol.y[i], label=nome)

    plt.title(f"Simulação AD — {var}")
    plt.xlabel("Tempo")
    plt.ylabel("Nível relativo")
    plt.legend()
    plt.show()

"""**Simulação 2 — PD: miR-7/miR-153 → SNCA → α-sinucleína → ROS → morte dopaminérgica**"""

# ======================================================
# SIMULAÇÃO 2 — VIA PD: miR-7 / miR-153 → SNCA → α-sinucleína
# ======================================================

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# y[0] = SNCA
# y[1] = alfa-sinucleína agregada
# y[2] = estresse oxidativo / ROS
# y[3] = sobrevivência dopaminérgica

def modelo_PD(t, y, mirna, params):
    SNCA, alpha_syn, ROS, neuron = y

    dSNCA_dt = (
        params["alpha_snca"]
        - params["beta_mirna"] * mirna * SNCA
        - params["delta_snca"] * SNCA
    )

    dAlpha_dt = (
        params["alpha_alpha"] * SNCA
        - params["delta_alpha"] * alpha_syn
    )

    dROS_dt = (
        params["alpha_ros"] * alpha_syn
        - params["delta_ros"] * ROS
    )

    dNeuron_dt = - params["beta_neuron"] * ROS * neuron

    return [dSNCA_dt, dAlpha_dt, dROS_dt, dNeuron_dt]


params_PD = {
    "alpha_snca": 1.0,
    "beta_mirna": 0.75,
    "delta_snca": 0.12,
    "alpha_alpha": 0.65,
    "delta_alpha": 0.10,
    "alpha_ros": 0.45,
    "delta_ros": 0.08,
    "beta_neuron": 0.012
}

tempo = (0, 100)
t_eval = np.linspace(0, 100, 500)

condicoes_PD = {
    "Controle": 1.0,
    "Doença PD - baixo miRNA": 0.25,
    "Terapia mimic miR-7/miR-153": 1.8
}

resultados_PD = {}

for nome, mirna in condicoes_PD.items():
    sol = solve_ivp(
        modelo_PD,
        tempo,
        y0=[1.0, 0.4, 0.3, 1.0],
        t_eval=t_eval,
        args=(mirna, params_PD)
    )
    resultados_PD[nome] = sol

variaveis_PD = [
    "SNCA",
    "α-sinucleína agregada",
    "Estresse oxidativo / ROS",
    "Sobrevivência dopaminérgica"
]

for i, var in enumerate(variaveis_PD):
    plt.figure(figsize=(8, 5))

    for nome, sol in resultados_PD.items():
        plt.plot(sol.t, sol.y[i], label=nome)

    plt.xlabel("Tempo simulado")
    plt.ylabel("Nível relativo")
    plt.title(f"Simulação PD — {var}")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""**MODELO INTEGRADO AD + PD**"""

# ======================================================
# MODELO INTEGRADO — NEURODEGENERAÇÃO GLOBAL
# ======================================================

def modelo_integrado(t, y, mirna_AD, mirna_PD, params):
    BACE1, Abeta, inflam, SNCA, alpha_syn, ROS, neuron = y

    dBACE1 = params["a1"] - params["b1"]*mirna_AD*BACE1 - params["d1"]*BACE1
    dAbeta = params["a2"]*BACE1 - params["d2"]*Abeta
    dInflam = params["a3"]*Abeta - params["d3"]*inflam

    dSNCA = params["a4"] - params["b2"]*mirna_PD*SNCA - params["d4"]*SNCA
    dAlpha = params["a5"]*SNCA - params["d5"]*alpha_syn
    dROS = params["a6"]*alpha_syn - params["d6"]*ROS

    dNeuron = - params["b3"]*(inflam + ROS)*neuron

    return [dBACE1, dAbeta, dInflam, dSNCA, dAlpha, dROS, dNeuron]

# ======================================================
# EXECUÇÃO DO MODELO INTEGRADO AD + PD
# ======================================================

params_integrado = {
    "a1": 1.0,   # produção BACE1
    "b1": 0.8,   # repressão por miRNA AD
    "d1": 0.15,

    "a2": 0.7,   # produção Aβ por BACE1
    "d2": 0.12,

    "a3": 0.5,   # inflamação por Aβ
    "d3": 0.1,

    "a4": 1.0,   # produção SNCA
    "b2": 0.75,  # repressão por miRNA PD
    "d4": 0.12,

    "a5": 0.65,  # produção α-sinucleína
    "d5": 0.1,

    "a6": 0.45,  # ROS por α-sinucleína
    "d6": 0.08,

    "b3": 0.01   # morte neuronal por inflamação + ROS
}

tempo = (0, 100)
t_eval = np.linspace(0, 100, 500)

cenarios = {
    "Controle": (1.0, 1.0),
    "AD dominante": (0.25, 1.0),
    "PD dominante": (1.0, 0.25),
    "AD + PD combinadas": (0.25, 0.25),
    "Terapia combinada miRNA mimic": (1.8, 1.8)
}

resultados_integrado = {}

for nome, (mirna_AD, mirna_PD) in cenarios.items():
    sol = solve_ivp(
        modelo_integrado,
        tempo,
        y0=[1.0, 0.5, 0.3, 1.0, 0.4, 0.3, 1.0],
        t_eval=t_eval,
        args=(mirna_AD, mirna_PD, params_integrado)
    )
    resultados_integrado[nome] = sol

print("Simulações concluídas!")

variaveis_integradas = [
    "BACE1",
    "β-amiloide",
    "Neuroinflamação",
    "SNCA",
    "α-sinucleína",
    "ROS",
    "Sobrevivência neuronal global"
]

for i, var in enumerate(variaveis_integradas):
    plt.figure(figsize=(9, 5))

    for nome, sol in resultados_integrado.items():
        plt.plot(sol.t, sol.y[i], label=nome)

    plt.title(f"Modelo integrado AD + PD — {var}")
    plt.xlabel("Tempo simulado")
    plt.ylabel("Nível relativo")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""**Modelo 3D: “campo de neurodegeneração”**"""

import numpy as np
import plotly.graph_objects as go

inflam = np.linspace(0, 100, 100)
ros = np.linspace(0, 120, 100)

INFLAM, ROS = np.meshgrid(inflam, ros)

# modelo simplificado de sobrevivência neuronal
SURVIVAL = np.exp(-0.025 * INFLAM - 0.018 * ROS)

fig = go.Figure(data=[
    go.Surface(
        x=INFLAM,
        y=ROS,
        z=SURVIVAL,
        colorscale="Viridis"
    )
])

fig.update_layout(
    title="Paisagem 3D da neurodegeneração: inflamação, ROS e sobrevivência neuronal",
    scene=dict(
        xaxis_title="Neuroinflamação",
        yaxis_title="Estresse oxidativo / ROS",
        zaxis_title="Sobrevivência neuronal"
    ),
    width=900,
    height=700
)

fig.show()

import numpy as np
import plotly.graph_objects as go

inflam = np.linspace(0, 100, 100)
ros = np.linspace(0, 120, 100)

INFLAM, ROS = np.meshgrid(inflam, ros)

SURVIVAL = np.exp(-0.025 * INFLAM - 0.018 * ROS)

# Classificação em regiões
zone = np.zeros_like(SURVIVAL)

zone[SURVIVAL > 0.6] = 2   # saudável
zone[(SURVIVAL <= 0.6) & (SURVIVAL > 0.3)] = 1  # intermediário
zone[SURVIVAL <= 0.3] = 0  # degenerativo

fig = go.Figure()

fig.add_trace(go.Surface(
    x=INFLAM,
    y=ROS,
    z=SURVIVAL,
    surfacecolor=zone,
    colorscale=[
        [0, "red"],
        [0.5, "yellow"],
        [1, "green"]
    ],
    showscale=False
))

fig.update_layout(
    title="Mapa funcional da neurodegeneração (zonas biológicas)",
    scene=dict(
        xaxis_title="Neuroinflamação",
        yaxis_title="ROS",
        zaxis_title="Sobrevivência neuronal"
    )
)

fig.show()

# extrair dados reais do modelo integrado

sol = resultados_integrado["AD + PD combinadas"]

inflam_real = sol.y[2]
ros_real = sol.y[5]
survival_real = sol.y[6]

fig.add_trace(go.Scatter3d(
    x=inflam_real,
    y=ros_real,
    z=survival_real,
    mode='lines',
    line=dict(width=6),
    name='Progressão real AD+PD'
))

# terapia
sol_t = resultados_integrado["Terapia combinada miRNA mimic"]

fig.add_trace(go.Scatter3d(
    x=sol_t.y[2],
    y=sol_t.y[5],
    z=sol_t.y[6],
    mode='lines',
    line=dict(width=6),
    name='Terapia miRNA'
))

fig.show()

"""**heatmaps**"""

# ======================================================
# HEATMAPS PARA O TCC — miRNAs, doenças, amostras e métodos
# ======================================================

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# carregar base
top100 = pd.read_csv("top100_miRNA_AD_PD_annotated.csv")

# coluna de miRNAs
col_mirna = "miRNAs citados (auto)"

# função de extração e limpeza
def extract_and_clean(text):
    if pd.isna(text):
        return []

    mirs = re.findall(r'miR-\d+[a-zA-Z0-9\-]*', str(text))
    mirs = [m.rstrip('-').lower() for m in mirs]

    return mirs

top100["miRNAs_list"] = top100[col_mirna].apply(extract_and_clean)

# selecionar top miRNAs globais
all_mirnas = [m for sublist in top100["miRNAs_list"] for m in sublist]
top_mirnas = [m for m, c in Counter(all_mirnas).most_common(20)]

print("Top miRNAs usados nos heatmaps:")
print(top_mirnas)

# ======================================================
# HEATMAP 1 — miRNAs por doença
# ======================================================

groups = ["AD", "PD", "AD+PD"]

heatmap_data = []

for group in groups:
    subset = top100[top100["Doença (auto)"] == group]
    mirnas = [m for sublist in subset["miRNAs_list"] for m in sublist]
    counts = Counter(mirnas)
    heatmap_data.append([counts.get(m, 0) for m in top_mirnas])

df_heatmap_disease = pd.DataFrame(
    heatmap_data,
    index=groups,
    columns=top_mirnas
)

plt.figure(figsize=(16, 5))
sns.heatmap(
    df_heatmap_disease,
    annot=True,
    fmt="d",
    cmap="viridis",
    linewidths=0.5,
    linecolor="white"
)

plt.title("Frequência dos principais miRNAs por doença")
plt.xlabel("miRNAs")
plt.ylabel("Doença")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.savefig("heatmap_miRNAs_por_doenca.png", dpi=300, bbox_inches="tight")
plt.show()

# ======================================================
# HEATMAP 2 — miRNAs por tipo de amostra
# ======================================================

sample_col = "Amostra (auto)"

# expandir múltiplas amostras separadas por ;
rows = []

for _, row in top100.iterrows():
    samples = str(row[sample_col]).split(";")
    samples = [s.strip() for s in samples if s.strip() and s.strip() != "Indefinido"]

    for sample in samples:
        for mir in row["miRNAs_list"]:
            rows.append([sample, mir])

df_sample_mirna = pd.DataFrame(rows, columns=["Amostra", "miRNA"])

# manter só principais amostras e miRNAs
top_samples = df_sample_mirna["Amostra"].value_counts().head(8).index.tolist()
df_sample_mirna = df_sample_mirna[
    (df_sample_mirna["Amostra"].isin(top_samples)) &
    (df_sample_mirna["miRNA"].isin(top_mirnas))
]

df_heatmap_sample = pd.crosstab(
    df_sample_mirna["Amostra"],
    df_sample_mirna["miRNA"]
)

df_heatmap_sample = df_heatmap_sample.reindex(columns=top_mirnas, fill_value=0)

plt.figure(figsize=(16, 6))
sns.heatmap(
    df_heatmap_sample,
    annot=True,
    fmt="d",
    cmap="magma",
    linewidths=0.5,
    linecolor="white"
)

plt.title("Distribuição dos principais miRNAs por tipo de amostra")
plt.xlabel("miRNAs")
plt.ylabel("Tipo de amostra")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.savefig("heatmap_miRNAs_por_amostra.png", dpi=300, bbox_inches="tight")
plt.show()

# ======================================================
# HEATMAP 3 — miRNAs por método experimental
# ======================================================

method_col = "Método (auto)"

rows = []

for _, row in top100.iterrows():
    method = row[method_col]

    if pd.isna(method) or method == "Indefinido":
        continue

    for mir in row["miRNAs_list"]:
        rows.append([method, mir])

df_method_mirna = pd.DataFrame(rows, columns=["Método", "miRNA"])

df_method_mirna = df_method_mirna[
    df_method_mirna["miRNA"].isin(top_mirnas)
]

df_heatmap_method = pd.crosstab(
    df_method_mirna["Método"],
    df_method_mirna["miRNA"]
)

df_heatmap_method = df_heatmap_method.reindex(columns=top_mirnas, fill_value=0)

plt.figure(figsize=(16, 5))
sns.heatmap(
    df_heatmap_method,
    annot=True,
    fmt="d",
    cmap="cividis",
    linewidths=0.5,
    linecolor="white"
)

plt.title("Distribuição dos principais miRNAs por método experimental")
plt.xlabel("miRNAs")
plt.ylabel("Método experimental")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.savefig("heatmap_miRNAs_por_metodo.png", dpi=300, bbox_inches="tight")
plt.show()